setono_sylius_fragment_translation_admin_fragment_translation:
    resource: |
        alias: setono_sylius_fragment_translation.fragment_translation
        section: admin
        templates: SyliusAdminBundle:Crud
        redirect: update
        grid: setono_sylius_fragment_translation_admin_fragment_translation
        vars:
            all:
                subheader: setono_sylius_fragment_translation.ui.manage_fragment_translations
            index:
                icon: 'language'
    type: sylius.resource
