imports:
    - "@SetonoSyliusFragmentTranslationPlugin/Resources/config/grids/setono_sylius_fragment_translation_admin_fragment_translation.yaml"

framework:
    messenger:
        buses:
            setono_sylius_fragment_translation.command_bus: ~
